language: cpp
dist: trusty
sudo: required

compiler:
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libinsighttoolkit4-dev 
  - sudo apt-get install -qq libvtk6-dev libvtk6 
  - sudo apt-get install -qq cmake 
  - sudo apt-get install -qq gsl-bin libgsl0-dev 
  - sudo apt-get install -qq liblapack-dev liblapacke-dev 
  - sudo apt-get install -qq libopenblas-dev 

  # needed by vtk in some cases
  - sudo apt-get install -qq libpq-dev libpqxx-dev libpq5 
  - sudo find /usr/lib -name libpq.so 
  - sudo find /usr/lib -name libpq.so -exec ln -s {} /usr/lib/libpq.so ';' 

install:
  - git clone https://github.com/Slicer/SlicerExecutionModel.git 
  - mkdir SlicerExecutionModel-build 
  - cd SlicerExecutionModel-build 
  - cmake ../SlicerExecutionModel
  - make -j 4
  - cd ..

script:
  - mkdir build
  - cd build

  - export OPENBLAS_NUM_THREADS=1 && export OMP_NUM_THREADS=1 
  - cmake -DGenerateCLP_DIR=$(pwd)/../SlicerExecutionModel-build/GenerateCLP -DDMRITOOL_USE_MKL=OFF -DDMRITOOL_USE_FASTLAPACK=OFF -DDMRITOOL_USE_OPENMP=OFF -DBUILD_QT_APPLICATIONS=OFF -DDMRITOOL_WRAP_MATLAB=OFF -DCMAKE_CXX_FLAGS=-fpermissive -DVCL_CAN_STATIC_CONST_INIT_FLOAT=0 ..
  - make gtest_test -j 4 
  - make SphericalPolarFourierImaging 
  - make OrientationsViewer
  - make -j 3 utlVNLBlasGTest utlVNLLapackGTest utlNDArrayGTest
  - cd ./Modules/HelperFunctions/test/
  - ./utlVNLBlasGTest && ./utlVNLLapackGTest && ./utlNDArrayGTest 
  - cd ../../..
  - make -j 4

after_script:
  - ctest -VV

