language: cpp
sudo: required

compiler:
  - gcc

before_install:
  - sudo add-apt-repository ppa:zarquon42/precise-backports -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository ppa:staticfloat/julia-deps -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - sudo apt-get install -qq libinsighttoolkit4-dev 
  - sudo apt-get install -qq libvtk6-dev 
  - sudo apt-get install -qq cmake 
  - sudo apt-get install -qq gsl-bin libgsl0-dev 
  - sudo apt-get install -qq liblapack-dev liblapacke-dev 
  - sudo apt-get install -qq libopenblas-dev 

install:
  - git clone https://github.com/Slicer/SlicerExecutionModel.git 
  - mkdir SlicerExecutionModel-build 
  - cd SlicerExecutionModel-build 
  - cmake ../SlicerExecutionModel
  - make -j 4
  - cd ..

script:
  - mkdir build
  - cd build

  - export OPENBLAS_NUM_THREADS=1 && export OMP_NUM_THREADS=1 
  - cmake -DGenerateCLP_DIR=$(pwd)/../SlicerExecutionModel-build/GenerateCLP -DDMRITOOL_USE_MKL=OFF -DDMRITOOL_USE_FASTLAPACK=OFF -DDMRITOOL_USE_OPENMP=OFF -DBUILD_QT_APPLICATIONS=OFF -DDMRITOOL_WRAP_MATLAB=OFF -DCMAKE_CXX_FLAGS=-fpermissive -DVCL_CAN_STATIC_CONST_INIT_FLOAT=0 ..
  - make gtest_test -j 4 
  - make SphericalPolarFourierImaging 
  - make -j 3 utlVNLBlasGTest utlVNLLapackGTest utlNDArrayGTest
  - cd ./Modules/HelperFunctions/test/
  - ./utlVNLBlasGTest && ./utlVNLLapackGTest && ./utlNDArrayGTest 
  - cd ../../..
  - make -j 4

after_script:
  - ctest -VV

